//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.facturacion = new HashSet<facturacion>();
            this.nota_credito_venta = new HashSet<nota_credito_venta>();
        }
    
        public long id { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }

        [Required(ErrorMessage = "El apellido es requerido")]
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }

        [Required(ErrorMessage = "El numero de telefono es requerido")]
        [RegularExpression("^(?!0+$)(\\+\\d{1,3}[- ]?)?(?!0+$)\\d{8}$", ErrorMessage = "Ingrese el numero sin guiones.")]
        public string telefono { get; set; }

        [Required(ErrorMessage = "La direccion es requerida")]
        public string direccion { get; set; }
        public long MUNICIPIO_id { get; set; }

        [Required(ErrorMessage = "El numero de dui es requerido")]
        [RegularExpression("^(?!0+$)(\\+\\d{1,3}[- ]?)?(?!0+$)\\d{9}$", ErrorMessage = "Ingrese el numero sin guiones.")]
        public string num_dui { get; set; }

        [Required(ErrorMessage = "El email es requerido")]
        [EmailAddress(ErrorMessage = "El email no tiene el formato correcto")]
        public string email { get; set; }

        public string giro { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual ICollection<facturacion> facturacion { get; set; }
        public virtual ICollection<nota_credito_venta> nota_credito_venta { get; set; }
    }
}
