//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.m_compra = new HashSet<m_compra>();
            this.m_venta = new HashSet<m_venta>();
            this.m_orden_compra = new HashSet<m_orden_compra>();
            this.m_orden_compra1 = new HashSet<m_orden_compra>();
            this.usuario = new HashSet<usuario>();
        }
    
        public long id { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }

        [Required(ErrorMessage = "El apellido es requerido")]
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }

        [Required(ErrorMessage = "El numero de telefono es requerido")]
        [RegularExpression("^(?!0+$)(\\+\\d{1,3}[- ]?)?(?!0+$)\\d{8}$", ErrorMessage = "Ingrese el numero sin guiones.")]
        public string telefono { get; set; }

        [Required(ErrorMessage = "La direccion es requerida")]
        public string direccion { get; set; }
        public long MUNICIPIO_id { get; set; }
        public long SUCURSAL_id { get; set; }
        public Nullable<int> Caja_id { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual sucursal sucursal { get; set; }
        public virtual ICollection<m_compra> m_compra { get; set; }
        public virtual ICollection<m_venta> m_venta { get; set; }
        public virtual ICollection<m_orden_compra> m_orden_compra { get; set; }
        public virtual ICollection<m_orden_compra> m_orden_compra1 { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
