//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW_GASISW.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.m_compra = new HashSet<m_compra>();
            this.m_orden_compra = new HashSet<m_orden_compra>();
            this.producto = new HashSet<producto>();
        }
    
        public long id { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "El numero de telefono es requerido")]
        [RegularExpression("^(?!0+$)(\\+\\d{1,3}[- ]?)?(?!0+$)\\d{8}$", ErrorMessage = "Ingrese el numero sin guiones.")]
        public string telefono { get; set; }

        [Required(ErrorMessage = "El email es requerido")]
        [EmailAddress(ErrorMessage = "El email no tiene el formato correcto")]
        public string email { get; set; }

        [Required(ErrorMessage = "La direccion es requerida")]
        public string direccion { get; set; }
        public long MUNICIPIO_id { get; set; }
    
        public virtual ICollection<m_compra> m_compra { get; set; }
        public virtual ICollection<m_orden_compra> m_orden_compra { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
